//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.19 at 08:12:12 PM IST 
//


package ITS_MainController.DatabaseStubs;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class FactoryClass {

    public FactoryClass() {
    }

    public ShortestPathForResponse createShortestPathForResponse() {
        return new ShortestPathForResponse();
    }
    public ShortestPathForRequest createShortestPathForRequest() {
        return new ShortestPathForRequest();
    }

}
