//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.26 at 04:52:12 PM IST 
//


package ITS_MainController.DatabaseStubs;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ITS_MainController.DatabaseStubs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ITS_MainController.DatabaseStubs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShortestPathForResponse }
     * 
     */
    public ShortestPathForResponse createShortestPathForResponse() {
        return new ShortestPathForResponse();
    }

    /**
     * Create an instance of {@link ShortestPathForRequest }
     * 
     */
    public ShortestPathForRequest createShortestPathForRequest() {
        return new ShortestPathForRequest();
    }

}
